### ISSUE TITLE
谈谈对 RESTful 的认识 | Hello, Polebug

### ISSUE THREAD

**Issue by polebug** [polebug/polebug.github.io#18]
http://polebug.site/about-restful-api/ 

 还记得几个月前，我去面试的时候，面试官(也就是现在的同事)问了我一个问题：『你觉得什么是 RESTful？』，我当时的问答是：『RESTful API 都是围绕资源进行设计的，每个 URL 代表一种资源』，面试官补充说了一句：『 URL 里只能有名词，不能有动词。』   现在再去想这个问题，我很庆幸自己对 RESTful 的认识并不只停留在 API 的设计方面，下面详细的说说，我对 Rest

**Comment by IvanLuLyf** [comment]
RESTful 不是可以通过Request Method的语义去完成对资源的增删改查么
