### ISSUE TITLE
并发处理之异步任务 | Hello, Polebug

### ISSUE THREAD

**Issue by polebug** [polebug/polebug.github.io#19]
http://polebug.site/about-asyncio/ 

 我在实习过程中，最常见的一个场景就是高并发，那么如何处理高并发问题呢？  就拿我前几天写的需求来说吧，我需要给一些特定的用户推送特定的客服消息。推送消息这件事看起来简单，但是这里面还包含了很多额外的动作需要做，例如:   用户点击广告，未支付成功的时候：    把这个用户的 open id 塞到 redis 里 推送消息时候，我们需要去拿连接微信的 access token，调用微信的接口或者第

**Comment by gexiao** [comment]
一个 Worker 执行了任务，然后网络断了，没法告知消息队列自己已经把这个任务干完。然后会发生啥...

**Comment by polebug** [comment]
> @bynil
> 一个 Worker 执行了任务，然后网络断了，没法告知消息队列自己已经把这个任务干完。然后会发生啥...

如果是 RabbitMQ 的话，Worker 接到任务，这个任务会从 Queue 里删掉，完成任务之后，会返回 ack。如果中间出现异常，没有返回 ack，这个 message 会重发。
