### ISSUE TITLE
周报 ＃2 - 写在搬家之前 | Hello, Polebug

### ISSUE THREAD

**Issue by polebug** [polebug/polebug.github.io#48]
http://polebug.github.io/20230812/ 

 20230807 - 20230813 在即将搬家之际，我想好好写下这一年在深圳的感受。 文末仍然有本周的输入，不想看我碎碎念的朋友可以略过前面的内容 😛 “大海、随处可见的花、晴朗天空下大朵的云”我很喜欢深圳的大海、花和云，这大概是沿海城市的浪漫吧。 这一年里，最喜欢的事是，下午在海边的咖啡厅工作，傍晚下班了就去海边吹风，如果有晚霞的话就更好了。在海边发呆格外舒服，风很大，天空中的云变换得很快

**Comment by yorksome** [comment]
我要报名！@0xCavin

**Comment by polebug** [comment]
> @yorksome
> 我要报名！@0xCavin

收到咯

**Comment by DylanJinx** [comment]
期待采访
